name: Carrywiz
description: Packages Delivery App.

# version: 1.0.0+14
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  flutter_login_facebook: ^1.1.0
  firebase_core: ^1.6.0
  firebase_auth: ^3.1.0
  firebase_messaging: ^10.0.8
  # firebase_in_app_messaging: ^0.2.0+1
  google_sign_in: ^5.0.7
  font_awesome_flutter: ^9.1.0
  flutter_screenutil: ^5.0.0+2
  path_provider: ^2.0.2
  dio: ^4.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  rxdart: ^0.27.1
  flutter_launcher_icons: ^0.9.2
  provider: ^6.0.0
  flutter_cupertino_datetime_picker: ^2.0.1
  intl: ^0.17.0-nullsafety.2
  image_picker: ^0.8.4
  connectivity: ^3.0.6
  internet_connection_checker: ^0.0.1+2
  cached_network_image: ^3.1.0
  mime: ^1.0.0
#  toast: ^0.1.5
  toast:
    git:
      url: https://github.com/appdev/FlutterToast.git
  shared_preferences: ^2.0.7
#  flutter_secure_storage: ^3.3.4
  settings_ui: ^1.0.0
  http: ^0.13.3
  cupertino_icons: ^1.0.3
  google_fonts: ^2.1.0
  get_it: ^7.2.0
  expandable: ^5.0.1
  smooth_star_rating:
    git:
      url: https://github.com/bhavin-concetto/smoothratingbar.git
      ref: dev
  pull_to_refresh: ^2.0.0
  qr_flutter: ^4.0.0
#  qrscan: ^0.2.17
  barcode_scan2: ^4.1.4
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  country_code_picker: ^2.0.2
  share: ^2.0.4
  web_socket_channel: ^2.1.0
  # device_preview: ^0.4.8
  new_version: ^0.2.3
#  device_calendar: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/images/request_options/
    - assets/images/request_list/
    - assets/icons/
    - assets/data/
    - lang/en.json
    - lang/ar.json
  uses-material-design: true

#targets:
#  $default:
#    builders:
#      json_serializable:
#        options:
#          # Options configure how source code is generated for every
#          # `@JsonSerializable`-annotated class in the package.
#          #
#          # The default value for each is listed.
#          any_map: false
#          checked: false
#          create_factory: true
#          create_to_json: true
#          disallow_unrecognized_keys: false
#          explicit_to_json: false
#          field_rename: none
#          ignore_unannotated: false
#          include_if_null: true
#          nullable: true

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages